# Generated by Django 4.0 on 2023-12-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='comment_body',
        ),
    ]
