# Generated by Django 4.0 on 2023-12-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_rename_article_comment_comment_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=20)),
                ('content_creator', models.CharField(default='', max_length=20)),
                ('description', models.CharField(blank=True, default='', max_length=30)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
