# Generated by Django 4.0 on 2023-12-21 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_reels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reels',
            new_name='Reel',
        ),
    ]
