# Generated by Django 4.0 on 2024-01-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog_app', '0007_post_secondary_image_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='to_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
