# Generated by Django 4.0 on 2024-01-12 11:11

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog_app', '0008_comment_to_post_alter_comment_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='auth.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_body',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
